# Generated by Django 4.0.4 on 2022-05-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='OTP',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.IntegerField(max_length=255),
        ),
    ]
