# Generated by Django 4.0.4 on 2022-05-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_registration_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='OTP',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
