# Generated by Django 4.0.4 on 2022-05-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_registration_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='OTP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
